config/routes.rb
Rails.application.routes.draw do
  
  root 'landing_pages#index'

    get '/success' => 'landing_pages#success'

    get '/about_us' => 'landing_pages#about_us'

    get '/contact_us' => 'landing_pages#contact_us'

    get '/programs' => 'landing_pages#programs'

    resources :plans
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :description, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def index
  end

  def success
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  
  def index 
    @plans = Plan.all 
  end

  def new 
    @plan = Plan.new 
  end

  def create 
    @plan = Plan.create!(params[:plan])
    redirect_to plans_url 
  end 

  def update 
    @plan = Plan.find(params[:id])
    @plan.update_attributes!(params[:plan])
    redirect_to plans_url 
  end 

  def destroy 
    @plan = Plan.destroy(params[:id])
    redirect_to plans_url 
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/landing_pages/about_us.html.erb
<div class="welcome-content center-align">
   <h3 class="welcome-text">Welcome!</h3> 
  <main class="welcome-staff">
    <div class="container">  
      <header class="welcome-header">
        <%= image_tag("beastmode.jpeg", :class => "staff-image") %>
      </header>
      
      <h6 class="welcome-text">FOR THOSE WHO THINK FITNESS IS THE ULTIMATE PURSUIT
      WE'RE YOUR KIND OF FITNESS CENTER. IF YOU'RE WILLING TO PUT THE TIME AND EFFORT INTO MAXIMIZING YOUR FITNESS RESULTS, WE'RE WILLING TO GIVE YOU THE TOOLS TO ACHIEVE YOUR GOALS.  WE OFFER EXPERTS IN FITNESS, HEALTH, AND DIET, AND THE RIGHT EQUIPMENT (FREE WEIGHTS, MACHINES, EVERYTHING IN BETWEEN) AND THE RIGHT FACILITY (COMFORTABLE, CLEAN, HARD-CORE, WELL-LIT) TO PARTNER WITH YOU.
      </h6>
    </div>
    </main> 


<div class="staff-content center-align">
  <div class="row"> 
    <h3>Meet the staff</h3>
    <div class="col s4">
      <%= image_tag("cory-staff.jpeg", :class => "main-staff") %>
      <h5>Cory G.</h5> 
      <h5>Owner/Trainer</h5>
    </div> 
    <div class="col s4">
      <%= image_tag("matt-staff.jpeg", :class => "main-staff") %>
      <h5>Patrick S.</h5> 
      <h5>Webmaster/Client</h5>
    </div>
    <div class="col s4">
      <%= image_tag("patrick-staff.jpeg", :class => "main-staff") %>
      <h5>Matt C.</h5> 
      <h5>Owner XCELL Fitness</h5>
    </div>
  </div>
  </div>






<!-- footer content -->
<footer class="page-footer grey darken-4">
  <div class="container center-align">
    <div class="row">
      
      <h5 class="white-text">Bodybuilding | Fitness</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      
      <!-- social media links -->
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
      </ul>

    </div>
  </div>
  <div class="footer-copyright center-align">
    <div class="container">
      CG REVOLUTION | XCELL FITNESS © 2013 | ALL RIGHTS RESERVED 
    </div>
  </div>
</footer>
<!-- end of footer content -->

app/views/landing_pages/contact_us.html.erb
<form id="register" action="register.php" method="post" > 

  <h2>Register</h2> 
  <label for="name">Name</label><input type="text" id="name" name="name" /> 
  <label for="password">Password</label><input type="text" id="password" name="password" /> 
  <label for="message">Message</label><input type="text" id="message" name="message" /> 
  <input type="submit" value="Join" /> 

</form> 

app/views/landing_pages/index.html.erb
<!-- main content -->
<main class="main-content">
<h4> Welcome</h4>

  
  
  <!-- header content -->
  <header class="center-align">
 <h4> lajdfkjsf</h4>
  </header> 

</main>



<!-- footer content -->
<footer class="page-footer grey darken-4">
  <div class="container center-align">
    <div class="row">
      
      <h5 class="white-text">Bodybuilding | Fitness</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      
      <!-- social media links -->
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
      </ul>

    </div>
  </div>
  <div class="footer-copyright center-align">
    <div class="container">
      CG REVOLUTION | XCELL FITNESS © 2013 | ALL RIGHTS RESERVED 
    </div>
  </div>
</footer>
<!-- end of footer content -->

app/views/landing_pages/programs.html.erb
<!-- programs banner -->
<div class="parallax-container"> 
  <div class="parallax"><%= image_tag("dumbbells.jpg", :class => "programs") %></div>
</div>

<div class="program-content"> 
  <h3 class="center-align">Fitness Plans</h3> 
  <div class="row"> 
    <div class="col s4"> 
      <a id="tone_conditioning" href="tone.html"> 
      <%= image_tag("tone.jpg", :class => "toning") %></a> 
    </div> 
    <div class="col s4"> 
      <a id="weightloss" href="weightloss.html"> 
      <%= image_tag("weightloss.jpg", :class => "weightloss") %></a> 
    </div> 
    <div class="col s4"> 
      <a id="strength_conditioning" href="strength.html"> 
      <%= image_tag("cardio.png", :class => "strength") %></a> 
    </div> 
  </div> 
</div> 

app/views/landing_pages/success.html.erb
<!-- main content -->
<main class="main-content center-align">
  <header class="center-aligin">
    <h3 class="layout-text">Successes</h3> 
  </header>
  <!-- div containing the slider -->
  <div class="container slide-container">
    <!-- success photo slider -->
    <div class="slider">
      <ul class="slides">
        <li>
          <%= image_tag("success1.jpg", :class => "slide-show success-image") %>
        </li>
        <li> 
          <%= image_tag("success2.jpg", :class => "slide-show success-image") %> 
        </li>
        <li>
          <%= image_tag("success3.jpg", :class => "slide-show success-image") %> 
        </li>
        <li>
          <%= image_tag("success4.jpg", :class => "slide-show success-image") %> 
        </li>
      </ul>
    </div>
    <!-- end of success photo slider -->
  </div>

</main>
<!-- end of main content -->


<!-- footer content -->
<footer class="page-footer grey darken-4">
  <div class="container center-align">
    <div class="row">
      
      <h5 class="white-text">Bodybuilding | Fitness</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      
      <!-- social media links -->
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
      </ul>

    </div>
  </div>
  <div class="footer-copyright center-align">
    <div class="container">
      CG REVOLUTION | XCELL FITNESS © 2013 | ALL RIGHTS RESERVED 
    </div>
  </div>
</footer>

<script> 
  $(document).ready(function() { 
    $('.parallax').parallax(); 
}); 
</script> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Revfit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>

</head>
<body>



<!-- Fixed Navbar -->
<div class="navbar-fixed"> 
  
  <!-- Mobile Collapse Button -->
  <nav>
    <div class="nav-wrapper grey darken-4">
      <a href="#!" class="brand-logo">
        <%= image_tag("cgtitle.jpg", :class => "cgnav") %> 
      </a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Home', root_path %></li> 
        <li><%= link_to 'Successes', success_path %></li>
        <li><%= link_to 'About Us', about_us_path %></li> 
        <li><%= link_to 'Contact Us', contact_us_path %></li> 
        <li><%= link_to 'Programs', plans_path %></li> 
    
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Home</a></li>
        <li><a href="badges.html">Workouts</a></li>
        <li><a href="collapsible.html">Nutrition</a></li>
        <li><%= link_to 'Successes', success_path %></li>
        <li><%= link_to 'About Us', about_us_path %></li> 
        <li><%= link_to 'Contact Us', contact_us_path %></li> 
        <li><%= link_to 'Programs', programs_path %></li> 
      </ul>
    </div>
  </nav>

</div>
<!-- end of fixed navbar -->


<%= yield %>

</body>
</html>

app/views/plans/_form.html.erb
<%= simple_form_for @plan, remote: true do |f| %> 

  <%= f.input :description %> 
  <%= f.button :submit %> 
<% end %> 

app/views/plans/_plan.html.erb
<%= link_to edit_plan_path(plan), remote: true do %> 
  <button>Edit</button> 
<% end %> 

<%= link_to plan, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %> 
<% end %> 

app/views/plans/create.html.erb
<h1>Plans#create</h1>
<p>Find me in app/views/plans/create.html.erb</p>

app/views/plans/create.js.erb
$('body').append('<%= @plan.description %>'); 

app/views/plans/destroy.js.erb
$('.delete_plan').bind('ajax:success', function() { 
  $(this).closest('tr').fadeOut(); 
}); 

app/views/plans/index.html.erb
<div class="grid"> 
  <%= render 'sidebar_menu' %> 

  <%= render partials: 'plan_grid', locals: { plans: @plans} %> 
</div> 